apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
  namespace: platform-demo
data:
  PLATFORM_SERVICE_NAME: orders-service
  PLATFORM_ENVIRONMENT: local-kind
  PAYMENTS_SERVICE_BASE_URL: http://payments-service
