apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service-config
  namespace: platform-demo
data:
  PLATFORM_SERVICE_NAME: payments-service
  PLATFORM_ENVIRONMENT: local-kind
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
