spring:
  application:
    name: orders-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1-SNAPSHOT

logging:
  pattern:
    level: "%5p [%X{correlationId:-na},%X{traceId:-na},%X{spanId:-na}]"

platform:
  service:
    name: ${PLATFORM_SERVICE_NAME:orders-service}
    environment: ${PLATFORM_ENVIRONMENT:local}
  dependencies:
    payments:
      base-url: ${PAYMENTS_SERVICE_BASE_URL:http://localhost:8081}
  telemetry:
    otlp-endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
