Write-Host "Phase 1 bootstrap checklist:"
Write-Host "1. Create a local Kubernetes cluster with kind or minikube."
Write-Host "   Example: kind create cluster --config infra/local-cluster/kind-config.yaml"
Write-Host "2. Build both services with Maven using scripts/build-service.ps1."
Write-Host "3. Build the Docker images using scripts/build-images.ps1."
Write-Host "4. Load the images into your local cluster if needed."
Write-Host "   Example: kind load docker-image orders-service:phase1 --name platform-demo"
Write-Host "   Example: kind load docker-image payments-service:phase2 --name platform-demo"
Write-Host "5. Apply services and observability manifests using scripts/deploy-services.ps1."
